debug: mailx_utf-8 in tzm-sched

diff --git a/src/on_zone/tzm-sched b/src/on_zone/tzm-sched
--- a/src/on_zone/tzm-sched
+++ b/src/on_zone/tzm-sched
@@ -33,22 +33,48 @@ DSMC_ERROR_OK_RE=' ANS(1898I|1696W|1115W|1149E|1809W|2200I|2201I|2820E|1484I) '
 
 test -f /usr/local/bin/tzm-sched.conf && source /usr/local/bin/tzm-sched.conf
 
+# mmailx_utf-8()
+# # mailx_utf-8 is a sort of mailx which support utf-8
+# {
+#     SUBJECT="no subject given"
+#     while getopts ":s:" opt; do
+#         case $opt in
+#             s)
+#                 SUBJECT=$OPTARG
+#                 ;;
+#             *)
+#                 usage
+#                 ;;
+#         esac
+#     done
+#     shift $((OPTIND-1))
+#     RECIPIENTS="$@"   
+#     {
+#         cat << EOF
+# From: unix-bot@unige.ch
+# To: ${RECIPIENTS}
+# Subject: ${SUBJECT}
+# MIME-Version: 1.0
+# Content-Type: text/plain; charset="utf-8"
+# Content-Transfer-Encoding: 8bit
+# EOF
+#        cat -    
+#     } | /usr/sbin/sendmail ${RECIPIENTS} 
+# }
+
 mailx_utf-8()
 # mailx_utf-8 is a sort of mailx which support utf-8
 {
-    SUBJECT="no subject given"
-    while getopts ":s:" opt; do
-        case $opt in
-            s)
-                SUBJECT="$OPTARG"
-                ;;
-            *)
-                usage
-                ;;
-        esac
+    SUBJECT=""
+    while [[ "$1" = -* ]]; do
+      case "$1" in
+        -s|--subject)
+          SUBJECT=$2
+          shift 2
+          ;;
+      esac
     done
-    shift $((OPTIND-1))
-    RECIPIENTS="$@"   
+    RECIPIENTS="$@"
     {
         cat << EOF
 From: unix-bot@unige.ch
@@ -187,18 +213,22 @@ stop_service()
 
 pre()
 {
-	echo_verbose enter pre-tsm
-	#
+    echo_verbose "------------"
+    echo_verbose enter pre-tsm
+    echo_verbose "------------"
+    #
     # check that dsm-sched is disabled
     echo_verbose -n "check dsmc scheduler & dolly…"
     if ! svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
-        echo -e "\n✘ dsmc-sched should be disabled ✘" 
+        echo -e "\n✘ dsmc-sched should be disabled ✘"
+        echo "hint: clean $(basename $0) with $(basename $0) clean"
         exit 1
     fi
     #
     # check that dolly is not mounted
     if /usr/local/bin/dolly | ggrep -q "^mounted ${DOLLY_MOUNTPOINT}" ; then
         echo "\n✘ dolly should not be mounted ✘"
+        echo "hint: clean $(basename $0) with $(basename $0) clean"
         exit 2
     fi
     echo_verbose " ✔"
@@ -234,12 +264,82 @@ pre()
     echo_verbose " ✔"
     #
     #    
+    echo_verbose "------------"
     echo_verbose exit pre-tsm
+    echo_verbose "------------"
+}
+
+clean()
+{
+    echo "----------"
+    echo enter clean
+    echo "----------"
+    #
+    # dolly kill
+    echo "check if a clone is present"
+    if /usr/local/bin/dolly | ggrep -q "^mounted ${DOLLY_MOUNTPOINT}" ; then
+      echo -n " present! let's kill it…"
+      /usr/local/bin/dolly kill ${DOLLY_MOUNTPOINT}
+      if /usr/local/bin/dolly | ggrep -q "^mounted ${DOLLY_MOUNTPOINT}" ; then
+        echo "\n✘ unable to kill it"
+      else
+        echo " ✔"
+      fi
+    else
+      echo " ✔ not present"
+    fi
+    #
+    # disable dsmc-sched
+    echo "check if dsmc-sched is running…"
+    if ! svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
+        echo -n " running! let's stop it…"
+        svcadm disable -s dsmc-sched
+      if svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
+        echo " ✔"
+      else
+        echo "\n✘ unable to stop it"
+      fi
+    else
+      echo " ✔ not running"
+    fi
+    #
+    # remove directories
+    echo "check if the dir(${DOLLY_MOUNTPOINT}) exists"
+    if test -d ${DOLLY_MOUNTPOINT} ; then
+      if test -z "$(gfind ${DOLLY_MOUNTPOINT} ! -type d)" ; then
+        echo " ✘ no… but the dir(${DOLLY_MOUNTPOINT}) is constitued only of nested empty dir."
+        echo "   So, you can safely destroy them with : rm -fr ${DOLLY_MOUNTPOINT}"
+      else
+        echo " ✘ ouch, it seems that the mountpoint (${DOLLY_MOUNTPOINT}) is mounted."
+        echo "   This directory should not exist."
+        echo "   Please remove this mountpoint(${DOLLY_MOUNTPOINT}) carefully"
+      fi
+    else
+      echo " ✔ does not exists"
+    fi
+    #
+    # remove lock
+    echo "check if the lock (${DOLLY_MOUNTPOINT}.lock) is present"
+    if test -f ${DOLLY_MOUNTPOINT}.lock ; then
+      echo -n " it is. Let's remove it…"
+      if rm ${DOLLY_MOUNTPOINT}.lock ; then
+        echo " ✔"
+      else
+        echo "\n ✘ unable to remove the lock(${DOLLY_MOUNTPOINT}.lock)"
+      fi
+    else
+      echo " ✔ not present"
+    fi
+    echo "----------"
+    echo "exit clean"
+    echo "----------"
 }
 
 post()
 {
+    echo_verbose "------------"
     echo_verbose enter post-tsm
+    echo_verbose "------------"
     #
     # dolly kill
     echo_verbose -n "kill the clone…"
@@ -250,16 +350,18 @@ post()
     echo_verbose -n "parse the log and rotate it…"
     body_email=$(mktemp -p /tmp tzm-sched-email.XXXXXX)
     gegrep "${DSMC_ERROR_RE}" /var/log/dsmsched.log | gegrep -v "${DSMC_ERROR_OK_RE}" | cat > ${body_email}
-    logadm  -f /dev/null -C10 -N /var/log/dsmsched.log
+    #logadm-f /dev/null -C10 -N /var/log/dsmsched.log
+    logadm -f /dev/null -C10 -N -t '$file.%Y-%m-%d_%H:%M:%S' /var/log/dsmsched.log
     echo_verbose " ✔"
     if test -s ${body_email} ; then
-        echo_verbose "✘ error occured during the dsmc-sched ✘"
+        echo "✘ error occured during the dsmc-sched ✘"
+        echo "hint: clean $(basename $0) with $(basename $0) clean"
     fi
     #
     # send email
     echo_verbose -n "send email…"
     if test -s ${body_email} ; then
-        cat ${body_email} | mailx_utf-8 -s "[$(hostname | cut -d . -f1)] TSM Backup" ${EMAIL_DEST}
+        cat ${body_email} | mailx_utf-8 -s "[$(hostname)] TSM Backup" ${EMAIL_DEST}
     fi
     rm ${body_email}
     echo_verbose " ✔"
@@ -274,15 +376,18 @@ if ! svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
     exit 3
 fi
 EOF_AT
-	#
-	#
+    #
+    #
+    echo_verbose "------------"
     echo_verbose exit post-tsm
+    echo_verbose "------------"
 }
 
 usage () {
 	scriptname=$(basename ${0})
    cat <<EOF
 Usage: $scriptname pre-tsm | post-tsm
+       $scriptname clean
        $scriptname [-d] write_metadata4archive | delete_metadata4archive
    -h   displays basic help
    -v   verbose
@@ -290,6 +395,8 @@ Usage: $scriptname pre-tsm | post-tsm
 
 - pre-tsm/post-tsm are to be invoked if you want to backup with a scheduler
 in mind
+
+- clean is to be invoked when something get wrong and that it removes the well known problem
 
 - write_metadata4archive/delete_metadata4archive are a convenient way to access
 this function out of the use of pre-tsm/post-tsm
@@ -332,6 +439,9 @@ case $1 in
      ;;
    post-tsm)
      post
+     ;;
+   clean)
+     clean
      ;;
    write_metadata4archive)
      write_metadata4archive
